services:
  backend:
    image: singledigit-backend
    pull_policy: never
    container_name: singledigit-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    profiles:
      - dev
      - prod
    command: ["gunicorn", "singledigit.app:app", "-w", "4", "-b", "0.0.0.0:5000"]

  frontend-dev:
    image: node:14
    container_name: singledigit-frontend-dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: ["npm", "start"]
    profiles:
      - dev
    environment:
      - CHOKIDAR_USEPOLLING=true

  frontend-prod:
    image: frontend-prod
    pull_policy: never
    container_name: singledigit-frontend-prod
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    profiles:
      - prod

  mongodb:
    image: mongo:7.0.12
    container_name: singledigit-mongodb
    volumes:
      - mongodb-data:/data/db
    env_file:
      - ./mongodb/.env
    profiles:
      - dev
      - prod

  mongo-express:
    image: mongo-express:1.0.2
    ports:
      - 8081:8081
    container_name: singledigit-mongo-express
    env_file:
      - ./mongo-express/.env
    profiles:
      - dev


volumes:
  mongodb-data: